[phases.install]
cmds = [
    'mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx',
    'composer install --ignore-platform-reqs',
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@9.0.0 --activate",
    'pnpm i --frozen-lockfile',
]
