[phases.install]
cmds = [
    'mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx',
    'composer install --ignore-platform-reqs',
    'pnpm i --frozen-lockfile',
    "npm install -g corepack",
    "corepack enable",
    "corepack prepare pnpm@9.1.0 --activate",
    "pnpm install"
]
